apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guardrail-demo
  namespace: argocd
spec:
  project: guardrail
  source:
    repoURL: git@github.com:Davidpotters/guardrail.git
    targetRevision: main
    path: manifests/demo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
